### ISSUE TITLE
Optionally allow storing response body in run history

### ISSUE THREAD

**Issue by deepakpathania** [deepakpathania/Noah#17]
Accept an optional parameter in the create schedule API to decide whether or not to store response bodies in run history (false by default.)

Add a column to the `RunHistory` model and start storing the response body in case the option was sent as true.

**Comment by sagarchoudhary96** [comment]
@deepakpathania , i would like to take it up.

**Comment by deepakpathania** [comment]
Hey @sagarchoudhary96. Sure, go ahead. Assigning this to you, feel free to reach out in case you need any clarifications. 😄

**Comment by deepakpathania** [comment]
Addressed in #18. Closing.
